# Generated by Django 3.2.14 on 2022-08-02 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testing', '0020_testrunmaterializedmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PENDING', 'PENDING'), ('PREPARING', 'PREPARING'), ('PREPARED', 'PREPARED'), ('ERROR', 'ERROR'), ('SKIPPED', 'SKIPPED')], default='PENDING', max_length=128, verbose_name='state')),
                ('index', models.IntegerField(default=0)),
                ('from_date', models.DateTimeField(null=True, verbose_name='from datetime')),
                ('to_date', models.DateTimeField(null=True, verbose_name='to datetime')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Auto-generated field', verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Auto-generated and auto-updated field', verbose_name='updated')),
                ('test_suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='testing.testsuite')),
                ('tests', models.ManyToManyField(blank=True, to='testing.Test')),
            ],
            options={
                'verbose_name': 'dataset',
                'verbose_name_plural': 'datasets',
                'ordering': ['id', 'test_suite', 'index'],
                'unique_together': {('test_suite', 'index')},
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PENDING', 'PENDING'), ('TRAINING', 'TRAINING'), ('TRAINED', 'TRAINED'), ('ERROR', 'ERROR'), ('SKIPPED', 'SKIPPED')], default='PENDING', max_length=128, verbose_name='state')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Auto-generated field', verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Auto-generated and auto-updated field', verbose_name='updated')),
                ('datasets', models.ManyToManyField(blank=True, to='ml.MLDataset')),
                ('test_suite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='testing.testsuite')),
            ],
            options={
                'verbose_name': 'model',
                'verbose_name_plural': 'models',
                'ordering': ['id', 'test_suite'],
                'unique_together': {('test_suite',)},
            },
        ),
    ]
