# Generated by Django 3.2.10 on 2022-03-07 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testing', '0013_auto_20211229_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('UNKNOWN', 'UNKNOWN')], default='PENDING', max_length=128, verbose_name='status')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Auto-generated field', verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Auto-generated and auto-updated field', verbose_name='updated')),
                ('test_suite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='testing.testsuite', verbose_name='test_suite')),
            ],
            options={
                'verbose_name': 'model',
                'verbose_name_plural': 'models',
                'ordering': ['id', 'test_suite'],
            },
        ),
        migrations.CreateModel(
            name='MLDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS'), ('REJECTED', 'REJECTED'), ('FAILURE', 'FAILURE'), ('UNKNOWN', 'UNKNOWN')], default='PENDING', max_length=128, verbose_name='status')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Auto-generated field', verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Auto-generated and auto-updated field', verbose_name='updated')),
                ('test_suite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dataset', to='testing.testsuite', verbose_name='test_suite')),
            ],
            options={
                'verbose_name': 'dataset',
                'verbose_name_plural': 'datasets',
                'ordering': ['id', 'test_suite'],
            },
        ),
    ]
