# Generated by Django 3.2.12 on 2022-03-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='status',
            field=models.CharField(choices=[('DATASET_PENDING', 'DATASET_PENDING'), ('DATASET_PROCESSING', 'DATASET_PROCESSING'), ('DATASET_SUCCESS', 'DATASET_SUCCESS'), ('DATASET_FAILURE', 'DATASET_FAILURE'), ('DATASET_UNKNOWN', 'DATASET_UNKNOWN'), ('MODEL_PENDING', 'MODEL_PENDING'), ('MODEL_PROCESSING', 'MODEL_PROCESSING'), ('MODEL_SUCCESS', 'MODEL_SUCCESS'), ('MODEL_FAILURE', 'MODEL_FAILURE'), ('MODEL_UNKNOWN', 'MODEL_UNKNOWN'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=128, verbose_name='status'),
        ),
        migrations.DeleteModel(
            name='MLDataset',
        ),
    ]
