# Generated by Django 3.2.12 on 2022-03-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodel',
            name='status',
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='dataset_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=128, verbose_name='dataset status'),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='model_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=128, verbose_name='model status'),
        ),
    ]
