# Generated by Django 3.2.12 on 2022-06-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlmodel',
            old_name='fr',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='mlmodel',
            old_name='to',
            new_name='to_date',
        ),
    ]
