# Generated by Django 3.2.12 on 2022-07-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_auto_20220623_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='state',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PREPARING', 'PREPARING'), ('PREPARED', 'PREPARED'), ('TRAINING', 'TRAINING'), ('TRAINED', 'TRAINED'), ('ERROR', 'ERROR'), ('SKIPPED', 'SKIPPED')], default='PENDING', max_length=128, verbose_name='state'),
        ),
    ]
