# Generated by Django 3.2.12 on 2022-03-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_auto_20220314_1320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MLDataset',
        ),
    ]
