# Generated by Django 3.2.12 on 2022-04-05 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0018_auto_20220403_1514'),
        ('ml', '0003_delete_mldataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=128, verbose_name='status')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Auto-generated field', verbose_name='created')),
                ('updated', models.DateTimeField(auto_now_add=True, help_text='Auto-generated and auto-updated field', verbose_name='updated')),
                ('mlmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml.mlmodel')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.test')),
            ],
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='tests',
            field=models.ManyToManyField(blank=True, through='ml.MLModelTests', to='testing.Test', verbose_name='models'),
        ),
    ]
