# Generated by Django 3.2.12 on 2022-04-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0018_auto_20220403_1514'),
        ('ml', '0004_auto_20220405_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='mlmodels', through='ml.MLModelTests', to='testing.Test', verbose_name='models'),
        ),
    ]
