# Generated by Django 3.2.12 on 2022-04-07 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0018_auto_20220403_1514'),
        ('ml', '0006_alter_mlmodel_tests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mlmodel',
            options={'ordering': ['id', 'test_suite', 'test'], 'verbose_name': 'model', 'verbose_name_plural': 'models'},
        ),
        migrations.RemoveField(
            model_name='mlmodel',
            name='tests',
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='testing.test', verbose_name='test'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='test_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='testing.testsuite', verbose_name='test_suite'),
        ),
        migrations.DeleteModel(
            name='MLModelTests',
        ),
    ]
