# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-14 20:57
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0004_project_is_public'),
        ('testing', '0009_auto_20190902_1418'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Jira server url')),
                ('username', models.CharField(help_text='Jira username', max_length=255)),
                ('token', models.CharField(help_text='Jira personal token', max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_credentials', to='organization.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Jira Credential',
                'verbose_name_plural': 'Jira Credentials',
            },
        ),
        migrations.CreateModel(
            name='JiraIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.PositiveIntegerField()),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('defect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jira_issue', to='testing.Defect')),
            ],
            options={
                'verbose_name': 'Jira issue',
                'verbose_name_plural': 'Jira issues',
            },
        ),
        migrations.CreateModel(
            name='JiraProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_projects', to='jira_integration.JiraCredential')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jira_project', to='project.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Jira Project',
                'verbose_name_plural': 'Jira Projects',
            },
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='jira_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_issues', to='jira_integration.JiraProject'),
        ),
        migrations.AddIndex(
            model_name='jiraissue',
            index=models.Index(fields=['-issue_id'], name='jira_integr_issue_i_8db692_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jiracredential',
            unique_together=set([('organization', 'user', 'url')]),
        ),
    ]
