# Generated by Django 3.2.7 on 2021-09-14 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_organization_type'),
        ('testing', '0010_testsuite_ml_model_last_time_created'),
        ('project', '0005_project_auto_area_on_commit'),
        ('jira_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiracredential',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jira_credentials', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='jiracredential',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jira_credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='defect',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jira_issue', to='testing.defect'),
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='jira_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jira_issues', to='jira_integration.jiraproject'),
        ),
        migrations.AlterField(
            model_name='jiraproject',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jira_projects', to='jira_integration.jiracredential'),
        ),
        migrations.AlterField(
            model_name='jiraproject',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jira_project', to='project.project'),
        ),
        migrations.AlterField(
            model_name='jiraproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jira_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
