# Generated by Django 3.2.10 on 2021-12-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_integration', '0002_auto_20210914_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiracredential',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='extra_data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jiraproject',
            name='extra_data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='jiraproject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
