# Generated by Django 3.2.10 on 2021-12-29 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_20211214_1041'),
        ('project', '0009_auto_20211229_0055'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0013_auto_20211229_0055'),
        ('jira_integration', '0003_auto_20211208_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiracredential',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_credentials', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='jiracredential',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='defect',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jira_issue', to='testing.defect'),
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='jira_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_issues', to='jira_integration.jiraproject'),
        ),
        migrations.AlterField(
            model_name='jiraproject',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_projects', to='jira_integration.jiracredential'),
        ),
        migrations.AlterField(
            model_name='jiraproject',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jira_project', to='project.project'),
        ),
        migrations.AlterField(
            model_name='jiraproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
