# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-05 11:50
from __future__ import unicode_literals

import applications.project.base_models
import applications.project.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the project', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created', applications.project.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('updated', applications.project.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('slug', applications.project.fields.SlugField(blank=True, editable=False, help_text='The name in all lowercase, suitable for URL identification', max_length=200, populate_from='name', unique=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organization.Organization')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
            bases=(applications.project.base_models.UnicodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', applications.project.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('updated', applications.project.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='project.Project')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'project owner',
                'verbose_name_plural': 'project owners',
            },
            bases=(applications.project.base_models.UnicodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', applications.project.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('updated', applications.project.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_users', to='project.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_projectuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', 'user'],
                'abstract': False,
                'verbose_name_plural': 'project users',
                'verbose_name': 'project user',
            },
            bases=(applications.project.base_models.UnicodeMixin, models.Model),
        ),
        migrations.AddField(
            model_name='projectowner',
            name='project_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectUser'),
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='project_project', through='project.ProjectUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='projectuser',
            unique_together=set([('project', 'user')]),
        ),
    ]
