# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2021-04-19 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auto_area_on_commit',
            field=models.BooleanField(default=False),
        ),
    ]
