# Generated by Django 3.2.10 on 2021-12-29 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0008_alter_project_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectowner',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='project.project'),
        ),
        migrations.AlterField(
            model_name='projectowner',
            name='project_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.projectuser'),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_users', to='project.project'),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_projectuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
