# Generated by Django 3.2.12 on 2022-05-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20211229_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='time_saving',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
