# Generated by Django 3.2.12 on 2022-04-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20211229_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='subscription_paid_until',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
