# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-17 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('cloud', 'cloud'), ('standalone', 'standalone')], default='cloud', max_length=128),
        ),
    ]
