# Generated by Django 3.2.7 on 2021-09-14 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('organization', '0002_organization_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='organizationowner',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='organizationowner',
            name='organization_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='organization.organizationuser'),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization_users', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization_organizationuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
