# Generated by Django 3.2.12 on 2022-05-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_organization_subscription_paid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.CharField(choices=[('free-trial', 'Free-Trial'), ('free', 'Free'), ('plus', 'Plus'), ('pro', 'Professional')], default='free-trial', max_length=128),
        ),
        migrations.AddField(
            model_name='organization',
            name='time_saving_left',
            field=models.IntegerField(blank=True, default=60000, help_text='Time saving left in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_paid_until',
            field=models.IntegerField(blank=True, default=1660644714, null=True),
        ),
    ]
