# Generated by Django 3.2.12 on 2022-05-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20220518_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subscription_paid_until',
            field=models.IntegerField(blank=True, default=1661209625, null=True),
        ),
    ]
