# Generated by Django 3.2.12 on 2022-07-06 15:40

import applications.organization.abstract_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_alter_organization_subscription_paid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subscription_paid_until',
            field=models.IntegerField(blank=True, default=applications.organization.abstract_models._90days_trial, null=True),
        ),
    ]
