# Generated by Django 3.2.7 on 2021-09-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('github', 'GitHub'), ('google', 'Google'), ('bitbucket_oauth2', 'Bitbucket')], max_length=30, verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='socialapp',
            name='provider',
            field=models.CharField(choices=[('github', 'GitHub'), ('google', 'Google'), ('bitbucket_oauth2', 'Bitbucket')], max_length=30, verbose_name='provider'),
        ),
    ]
