# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-05 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitbucketHook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hook', models.CharField(max_length=38)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Bitbucket hook',
                'verbose_name_plural': 'Bitbucket hooks',
            },
        ),
        migrations.CreateModel(
            name='BitbucketIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bitbucket issue',
                'verbose_name_plural': 'Bitbucket issues',
            },
        ),
        migrations.CreateModel(
            name='BitbucketRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitbucket_repository_name', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Bitbucket repository',
                'verbose_name_plural': 'Bitbucket repositories',
            },
        ),
    ]
