# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-05 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('bitbucket_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitbucketrepository',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bitbucket_repository', to='project.Project'),
        ),
    ]
