# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-05 11:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialaccount', '0001_initial'),
        ('bitbucket_integration', '0002_bitbucketrepository_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitbucketrepository',
            name='social_token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialToken'),
        ),
        migrations.AddField(
            model_name='bitbucketrepository',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitbucket_repository', to=settings.AUTH_USER_MODEL),
        ),
    ]
