# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-05 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testing', '0001_initial'),
        ('project', '0001_initial'),
        ('bitbucket_integration', '0003_auto_20181105_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitbucketissue',
            name='defect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_bitbicket_issue', to='testing.Defect'),
        ),
        migrations.AddField(
            model_name='bitbuckethook',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bitbucket_web_hook', to='project.Project'),
        ),
    ]
