# Generated by Django 3.2.7 on 2021-09-14 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialaccount', '0002_auto_20210914_0844'),
        ('testing', '0010_testsuite_ml_model_last_time_created'),
        ('project', '0005_project_auto_area_on_commit'),
        ('bitbucket_integration', '0004_auto_20181105_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitbuckethook',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bitbucket_web_hook', to='project.project'),
        ),
        migrations.AlterField(
            model_name='bitbucketissue',
            name='defect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='_bitbicket_issue', to='testing.defect'),
        ),
        migrations.AlterField(
            model_name='bitbucketrepository',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bitbucket_repository', to='project.project'),
        ),
        migrations.AlterField(
            model_name='bitbucketrepository',
            name='social_token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='socialaccount.socialtoken'),
        ),
        migrations.AlterField(
            model_name='bitbucketrepository',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bitbucket_repository', to=settings.AUTH_USER_MODEL),
        ),
    ]
