# Generated by Django 3.2.10 on 2021-12-29 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20211229_0055'),
        ('socialaccount', '0003_auto_20211208_1836'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0013_auto_20211229_0055'),
        ('bitbucket_integration', '0006_auto_20211208_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitbuckethook',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bitbucket_web_hook', to='project.project'),
        ),
        migrations.AlterField(
            model_name='bitbucketissue',
            name='defect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_bitbicket_issue', to='testing.defect'),
        ),
        migrations.AlterField(
            model_name='bitbucketrepository',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bitbucket_repository', to='project.project'),
        ),
        migrations.AlterField(
            model_name='bitbucketrepository',
            name='social_token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialtoken'),
        ),
        migrations.AlterField(
            model_name='bitbucketrepository',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitbucket_repository', to=settings.AUTH_USER_MODEL),
        ),
    ]
