# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-05 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_repository_name', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.CharField(blank=True, default=b'22', max_length=6)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('path', models.TextField(blank=True)),
                ('is_installed_hook', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Git repository',
                'verbose_name_plural': 'Git repositories',
            },
        ),
    ]
