# Generated by Django 3.2.7 on 2021-09-14 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0005_project_auto_area_on_commit'),
        ('git_integration', '0002_auto_20181105_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitrepository',
            name='port',
            field=models.CharField(blank=True, default='22', max_length=6),
        ),
        migrations.AlterField(
            model_name='gitrepository',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='git_repository', to='project.project'),
        ),
        migrations.AlterField(
            model_name='gitrepository',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='local_repository', to=settings.AUTH_USER_MODEL),
        ),
    ]
