#!/bin/bash

set -o errexit
set -o nounset

rm -f '/opt/app/pids/celery-events.pid'
/usr/local/bin/celery events -A system --camera django_celery_monitor.camera.Camera --frequency=15.0 --loglevel=INFO \
--pidfile /opt/app/pids/celery-events.pid