# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitSSHRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_name', models.CharField(max_length=255)),
                ('url_repository', models.CharField(max_length=512)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='git_ssh_repository', to='project.Project')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Git SSH repository',
                'verbose_name_plural': 'Git SSH repositories',
            },
        ),
    ]
