# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_ssh_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitsshrepository',
            name='private_key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
