# Generated by Django 3.2.7 on 2021-09-14 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_auto_area_on_commit'),
        ('git_ssh_integration', '0002_gitsshrepository_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitsshrepository',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='git_ssh_repository', to='project.project'),
        ),
    ]
