# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-05 11:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('github_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepository',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_repository', to='project.Project'),
        ),
        migrations.AddField(
            model_name='githubrepository',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_repository', to=settings.AUTH_USER_MODEL),
        ),
    ]
