# Generated by Django 3.2.10 on 2021-12-29 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20211208_1836'),
        ('github_integration', '0005_auto_20211208_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepository',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_repository', to='project.project'),
        ),
    ]
