# Generated by Django 3.2.10 on 2021-12-29 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20211229_0055'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0013_auto_20211229_0055'),
        ('github_integration', '0006_alter_githubrepository_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubhook',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='web_hook', to='project.project'),
        ),
        migrations.AlterField(
            model_name='githubissue',
            name='defect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='testing.defect'),
        ),
        migrations.AlterField(
            model_name='githubrepository',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_repository', to=settings.AUTH_USER_MODEL),
        ),
    ]
