# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-05 11:50
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('usage', models.CharField(blank=True, max_length=255)),
                ('priority', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='project.Project')),
            ],
            options={
                'verbose_name': 'area',
                'verbose_name_plural': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='master', max_length=255)),
                ('sha', models.CharField(blank=True, default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='project.Project')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.CharField(blank=True, default='', max_length=255)),
                ('sha', models.CharField(blank=True, default='', max_length=255)),
                ('display_id', models.CharField(default='0000000', max_length=255)),
                ('url', models.URLField(blank=True, default=b'', max_length=255)),
                ('author', django.contrib.postgres.fields.jsonb.JSONField(default={b'email': b'', b'first_name': b'', b'last_name': b'', b'username': b''})),
                ('committer', django.contrib.postgres.fields.jsonb.JSONField(default={b'email': b'', b'first_name': b'', b'last_name': b'', b'username': b''})),
                ('message', models.CharField(blank=True, default=b'', max_length=255)),
                ('stats', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={b'additions': 0, b'deletions': 0, b'total': 0})),
                ('tree', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={b'sha': '', b'url': ''})),
                ('rework', models.IntegerField(default=0)),
                ('output', models.IntegerField(default=0)),
                ('riskiness', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('areas', models.ManyToManyField(blank=True, related_name='commits', to='vcs.Area')),
                ('branches', models.ManyToManyField(blank=True, related_name='commits', to='vcs.Branch')),
            ],
            options={
                'verbose_name': 'commit',
                'verbose_name_plural': 'commits',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(blank=True, default='', max_length=255)),
                ('filename', models.CharField(blank=True, default='', max_length=4096)),
                ('full_filename', models.CharField(blank=True, default='', max_length=4096)),
                ('raw_url', models.URLField(blank=True, default=b'', max_length=4096)),
                ('blob_url', models.URLField(blank=True, default=b'', max_length=4096)),
                ('contents_url', models.URLField(blank=True, default=b'', max_length=4096)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('areas', models.ManyToManyField(blank=True, related_name='files', to='vcs.Area')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='vcs.File')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='project.Project')),
            ],
            options={
                'verbose_name': 'Project file',
                'verbose_name_plural': 'Project files',
            },
        ),
        migrations.CreateModel(
            name='FileChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('changes', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'added'), (2, 'modified'), (3, 'deleted'), (4, 'renamed')], default=1)),
                ('patch', models.TextField(blank=True, default='')),
                ('previous_filename', models.CharField(blank=True, default='', max_length=4096)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs.Commit')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs.File')),
            ],
            options={
                'verbose_name': 'project file changes',
                'verbose_name_plural': 'project file changes',
            },
        ),
        migrations.CreateModel(
            name='ParentCommit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('from_commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_commits', to='vcs.Commit')),
                ('to_commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_commits', to='vcs.Commit')),
            ],
            options={
                'verbose_name': 'parent commit',
                'verbose_name_plural': 'parent commits',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='0.0.1', max_length=255)),
                ('sha', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.URLField(blank=True, default=b'', max_length=255)),
                ('tagger', django.contrib.postgres.fields.jsonb.JSONField(default={b'email': b'', b'first_name': b'', b'last_name': b'', b'username': b''})),
                ('message', models.CharField(blank=True, default=b'', max_length=255)),
                ('target_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('areas', models.ManyToManyField(blank=True, related_name='tags', to='vcs.Area')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='project.Project')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.AddField(
            model_name='commit',
            name='files',
            field=models.ManyToManyField(blank=True, through='vcs.FileChange', to='vcs.File'),
        ),
        migrations.AddField(
            model_name='commit',
            name='parents',
            field=models.ManyToManyField(blank=True, through='vcs.ParentCommit', to='vcs.Commit'),
        ),
        migrations.AddField(
            model_name='commit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='project.Project'),
        ),
        migrations.AddField(
            model_name='commit',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('target_type', 'target_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set([('project', 'filename', 'parent')]),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together=set([('project', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together=set([('project', 'name')]),
        ),
    ]
