# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-07 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filechange',
            name='blame',
            field=models.TextField(blank=True, default=''),
        ),
    ]
