# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-29 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0003_auto_20190814_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='_area_dependencies_+', to='vcs.Area'),
        ),
    ]
