# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-24 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0004_area_dependencies'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['-timestamp'], name='vcs_commit_timesta_ef606d_idx'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['sha'], name='vcs_commit_sha_4b5303_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['full_filename'], name='vcs_file_full_fi_ee6e6e_idx'),
        ),
    ]
