# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-24 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0005_auto_20190924_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='_area_links_+', to='vcs.Area'),
        ),
    ]
