# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-27 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0006_auto_20191027_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='depended_on', to='vcs.Area'),
        ),
        migrations.AlterField(
            model_name='area',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='linked_to', to='vcs.Area'),
        ),
    ]
