# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-10-06 17:45
from __future__ import unicode_literals

from django.db import migrations, models


def set_type_folder(apps, schema_editor):
    AreaModel = apps.get_model('vcs', 'Area')
    AreaModel.objects.exclude(name='Default Area').update(type=1)


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0007_auto_20200127_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='type',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'folder'), (2, 'code')], default=0),
        ),
        migrations.RunPython(set_type_folder),
    ]
