# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2021-02-02 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_is_public'),
        ('vcs', '0008_area_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commit',
            unique_together=set([('project', 'sha')]),
        ),
    ]
