# Generated by Django 3.2.7 on 2021-09-14 08:44

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0006_auto_20210914_0844'),
        ('vcs', '0009_auto_20210202_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='areas', to='project.project'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='branches', to='project.project'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='author',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'first_name': '', 'last_name': '', 'username': ''}),
        ),
        migrations.AlterField(
            model_name='commit',
            name='committer',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'first_name': '', 'last_name': '', 'username': ''}),
        ),
        migrations.AlterField(
            model_name='commit',
            name='message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='commit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='commits', to='project.project'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commit',
            name='stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'additions': 0, 'deletions': 0, 'total': 0}),
        ),
        migrations.AlterField(
            model_name='commit',
            name='tree',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'sha': '', 'url': ''}),
        ),
        migrations.AlterField(
            model_name='commit',
            name='url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='blob_url',
            field=models.URLField(blank=True, default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='file',
            name='contents_url',
            field=models.URLField(blank=True, default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='file',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='files', to='project.project'),
        ),
        migrations.AlterField(
            model_name='file',
            name='raw_url',
            field=models.URLField(blank=True, default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='file',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='filechange',
            name='commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vcs.commit'),
        ),
        migrations.AlterField(
            model_name='filechange',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vcs.file'),
        ),
        migrations.AlterField(
            model_name='parentcommit',
            name='from_commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_commits', to='vcs.commit'),
        ),
        migrations.AlterField(
            model_name='parentcommit',
            name='to_commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_commits', to='vcs.commit'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tags', to='project.project'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagger',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'email': '', 'first_name': '', 'last_name': '', 'username': ''}),
        ),
        migrations.AlterField(
            model_name='tag',
            name='url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
