# Generated by Django 3.2.10 on 2021-12-08 18:36

import applications.vcs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0010_auto_20210914_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='author',
            field=models.JSONField(default=applications.vcs.models.get_default_user_dict),
        ),
        migrations.AlterField(
            model_name='commit',
            name='committer',
            field=models.JSONField(default=applications.vcs.models.get_default_user_dict),
        ),
        migrations.AlterField(
            model_name='commit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='stats',
            field=models.JSONField(blank=True, default=applications.vcs.models.get_default_stats),
        ),
        migrations.AlterField(
            model_name='commit',
            name='tree',
            field=models.JSONField(blank=True, default=applications.vcs.models.get_default_tree),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='filechange',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parentcommit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagger',
            field=models.JSONField(default=applications.vcs.models.get_default_user_dict),
        ),
    ]
