# Generated by Django 3.2.12 on 2022-05-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0014_auto_20220403_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
