# Generated by Django 3.2.7 on 2021-09-14 08:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_type'),
        ('license', '0002_populate_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='license_keys', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
