# Generated by Django 3.2.12 on 2022-04-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_role', '0002_userrole_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='index',
            field=models.IntegerField(default=99),
        ),
    ]
