# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0001_initial'),
        ('testing', '0002_auto_20181105_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='associated_areas',
            field=models.ManyToManyField(blank=True, related_name='associated_areas', to='vcs.Area'),
        ),
        migrations.AddField(
            model_name='test',
            name='associated_files',
            field=models.ManyToManyField(blank=True, related_name='associated_files', to='vcs.File'),
        ),
    ]
