# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-09 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_auto_20190515_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='mix_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
