# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-22 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0001_initial'),
        ('testing', '0004_test_mix_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='closed_by_commits',
            field=models.ManyToManyField(blank=True, related_name='closed_by_defects', to='vcs.Commit'),
        ),
    ]
