# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-31 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_defect_closed_by_commits'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='class_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='testsuite_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
