# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_auto_20190731_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='original_defect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reopened_defect', to='testing.Defect'),
        ),
    ]
