# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-02 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_defect_original_defect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrunresult',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testrunresult',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='testrunresult',
            index=models.Index(fields=['-created'], name='testrunresult_created_idx'),
        ),
    ]
