# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-02 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_auto_20190902_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='type',
            field=models.IntegerField(choices=[(1, 'ENVIRONMENTAL'), (2, 'FLAKY'), (3, 'PROJECT'), (4, 'INVALID TEST'), (5, 'LOCAL'), (6, 'OUTSIDE SCOPE')], default=1),
        ),
    ]
