# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-07 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_auto_20190902_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='ml_model_last_time_created',
            field=models.DateTimeField(null=True),
        ),
    ]
