# Generated by Django 3.2.7 on 2021-09-14 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0010_auto_20210914_0844'),
        ('project', '0006_auto_20210914_0844'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0010_testsuite_ml_model_last_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='close_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='defect',
            name='closed_commit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='closed_defects', to='vcs.commit'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='closed_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='closed_defects', to='testing.test'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='closed_test_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='closed_defects', to='testing.testrun'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='closed_test_run_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='closed_defects', to='testing.testrunresult'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='closed_test_suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='closed_defects', to='testing.testsuite'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='created_by_commit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_defects', to='vcs.commit'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='created_by_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_defects', to='testing.test'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='created_by_test_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_defects', to='testing.testrun'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='created_by_test_run_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_defects', to='testing.testrunresult'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='created_by_test_suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_defects', to='testing.testsuite'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='original_defect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reopened_defect', to='testing.defect'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_defects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='defect',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='defects', to='project.project'),
        ),
        migrations.AlterField(
            model_name='step',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='steps', to='project.project'),
        ),
        migrations.AlterField(
            model_name='test',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tests', to='vcs.area'),
        ),
        migrations.AlterField(
            model_name='test',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tests', to='project.project'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='commit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_runs', to='vcs.commit'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_runs', to='project.project'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='test_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_runs', to='testing.testsuite'),
        ),
        migrations.AlterField(
            model_name='testrunresult',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_run_results', to='vcs.area'),
        ),
        migrations.AlterField(
            model_name='testrunresult',
            name='commit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_run_results', to='vcs.commit'),
        ),
        migrations.AlterField(
            model_name='testrunresult',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_run_results', to='project.project'),
        ),
        migrations.AlterField(
            model_name='testrunresult',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_run_results', to='testing.step'),
        ),
        migrations.AlterField(
            model_name='testrunresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_run_results', to='testing.test'),
        ),
        migrations.AlterField(
            model_name='testrunresult',
            name='test_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_run_results', to='testing.testrun'),
        ),
        migrations.AlterField(
            model_name='testrunresult',
            name='test_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_run_results', to='testing.testsuite'),
        ),
        migrations.AlterField(
            model_name='testrunresult',
            name='test_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_run_results', to='testing.testtype'),
        ),
        migrations.AlterField(
            model_name='testrunresultattachment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_run_result_attachments', to='project.project'),
        ),
        migrations.AlterField(
            model_name='testrunresultattachment',
            name='test_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_run_result_attachments', to='testing.testrun'),
        ),
        migrations.AlterField(
            model_name='testrunresultattachment',
            name='test_run_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_run_result_attachments', to='testing.testrunresult'),
        ),
        migrations.AlterField(
            model_name='testrunresultattachment',
            name='test_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_run_result_attachments', to='testing.testsuite'),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testing.step'),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testing.test'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='location_of_tests',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_suites', to='project.project'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='test_suite_endpoint',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='test_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_suites', to='testing.testtype'),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_types', to='project.project'),
        ),
    ]
