# Generated by Django 3.2.12 on 2022-03-10 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20211229_0055'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vcs', '0012_auto_20211229_0055'),
        ('testing', '0013_auto_20211229_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='closed_commit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_defects', to='vcs.commit'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='closed_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_defects', to='testing.test'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='closed_test_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_defects', to='testing.testrun'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='closed_test_run_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_defects', to='testing.testrunresult'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='closed_test_suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_defects', to='testing.testsuite'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='created_by_commit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_defects', to='vcs.commit'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='created_by_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_defects', to='testing.test'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='created_by_test_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_defects', to='testing.testrun'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='created_by_test_run_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_defects', to='testing.testrunresult'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='created_by_test_suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_defects', to='testing.testsuite'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='original_defect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reopened_defect', to='testing.defect'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_defects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='defect',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='project.project'),
        ),
        migrations.AlterField(
            model_name='testrunresult',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_run_results', to='vcs.area'),
        ),
        migrations.AlterField(
            model_name='testrunresult',
            name='commit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_run_results', to='vcs.commit'),
        ),
        migrations.AlterField(
            model_name='testrunresult',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_run_results', to='testing.step'),
        ),
        migrations.AlterField(
            model_name='testrunresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_run_results', to='testing.test'),
        ),
        migrations.AlterField(
            model_name='testrunresult',
            name='test_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_run_results', to='testing.testrun'),
        ),
        migrations.AlterField(
            model_name='testrunresultattachment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_run_result_attachments', to='project.project'),
        ),
        migrations.AlterField(
            model_name='testrunresultattachment',
            name='test_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_run_result_attachments', to='testing.testrun'),
        ),
        migrations.AlterField(
            model_name='testrunresultattachment',
            name='test_run_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_run_result_attachments', to='testing.testrunresult'),
        ),
        migrations.AlterField(
            model_name='testrunresultattachment',
            name='test_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_run_result_attachments', to='testing.testsuite'),
        ),
    ]
