# Generated by Django 3.2.12 on 2022-03-28 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0012_auto_20211229_0055'),
        ('testing', '0015_auto_20220321_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testreport',
            options={'ordering': ['-id', '-project', '-test_suite'], 'verbose_name': 'test report', 'verbose_name_plural': 'test reports'},
        ),
        migrations.CreateModel(
            name='DefectCausedByCommits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Auto-generated field', verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Auto-generated and auto-updated field', verbose_name='updated')),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs.commit')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.defect')),
            ],
            options={
                'db_table': 'testing_defect_caused_by_commits',
            },
        ),
        migrations.AlterField(
            model_name='defect',
            name='caused_by_commits',
            field=models.ManyToManyField(blank=True, related_name='caused_defects', through='testing.DefectCausedByCommits', to='vcs.Commit'),
        ),
    ]





class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=16, null=True)),
                ('game_day', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.team')),
            ],
        ),
        migrations.AlterModelTable(
            name='roster',
            table='example_team_players',
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(through='example.Roster', to='example.Player'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        migrations.AddField(
            model_name='Roster',
            name='position',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='Roster',
            name='game_day',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='roster',
            table=None,
        ),
    ]