# Generated by Django 3.2.12 on 2022-03-28 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0012_auto_20211229_0055'),
        ('testing', '0015_auto_20220321_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testreport',
            options={'ordering': ['-id', '-project', '-test_suite'], 'verbose_name': 'test report', 'verbose_name_plural': 'test reports'},
        ),

    ]
