# Generated by Django 3.2.12 on 2022-03-29 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0012_auto_20211229_0055'),
        ('testing', '0016_auto_20220328_1317'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='DefectCausedByCommits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created',
                 models.DateTimeField(auto_now_add=True, help_text='Auto-generated field', verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Auto-generated and auto-updated field',
                                                 verbose_name='updated')),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs.commit')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.defect')),
            ],
            options={
                'db_table': 'testing_defect_caused_by_commits',
            },
        ),
        migrations.AlterModelTable(
            name='defectcausedbycommits',
            table='testing_defect_caused_by_commits'
        ),
        migrations.AlterField(
            model_name='defect',
            name='caused_by_commits',
            field=models.ManyToManyField(blank=True, related_name='caused_defects', through='testing.DefectCausedByCommits', to='vcs.Commit'),
        ),
        migrations.CreateModel(
            name='DefectClosedByCommits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created',
                 models.DateTimeField(auto_now_add=True, help_text='Auto-generated field', verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Auto-generated and auto-updated field',
                                                 verbose_name='updated')),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs.commit')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.defect')),
            ],
            options={
                'db_table': 'testing_defect_closed_by_commits',
            },
        ),
        migrations.AlterModelTable(
            name='defectclosedbycommits',
            table='testing_defect_closed_by_commits'
        ),
        migrations.AlterField(
            model_name='defect',
            name='closed_by_commits',
            field=models.ManyToManyField(blank=True, related_name='closed_by_defects',
                                         through='testing.DefectClosedByCommits', to='vcs.Commit'),
        ),
        migrations.CreateModel(
            name='TestAssociatedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created',
                 models.DateTimeField(auto_now_add=True, help_text='Auto-generated field', verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Auto-generated and auto-updated field',
                                                 verbose_name='updated')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs.file')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.test')),
            ],
            options={
                'db_table': 'testing_test_associated_files',
            },
        ),
        migrations.AlterModelTable(
            name='testassociatedfiles',
            table='testing_test_associated_files'
        ),
        migrations.AlterField(
            model_name='test',
            name='associated_files',
            field=models.ManyToManyField(blank=True, related_name='associated_files',
                                         through='testing.TestAssociatedFiles', to='vcs.File'),
        ),
        migrations.CreateModel(
            name='TestAssociatedAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created',
                 models.DateTimeField(auto_now_add=True, help_text='Auto-generated field', verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Auto-generated and auto-updated field',
                                                 verbose_name='updated')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs.area')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.test')),
            ],
            options={
                'db_table': 'testing_test_associated_areas',
            },
        ),
        migrations.AlterModelTable(
            name='testassociatedareas',
            table='testing_test_associated_areas'
        ),
        migrations.AlterField(
            model_name='test',
            name='associated_areas',
            field=models.ManyToManyField(blank=True, related_name='associated_areas',
                                         through='testing.TestAssociatedAreas', to='vcs.Area'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),

        migrations.AddField(
            model_name='DefectCausedByCommits',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Auto-generated field', verbose_name='created'),
        ),
        migrations.AddField(
            model_name='DefectCausedByCommits',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Auto-generated and auto-updated field',
                                       verbose_name='updated'),
        ),
        migrations.AlterModelTable(
            name='defectcausedbycommits',
            table='testing_defect_caused_by_commits',
        ),
        migrations.AddField(
            model_name='DefectClosedByCommits',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Auto-generated field', verbose_name='created'),
        ),
        migrations.AddField(
            model_name='DefectClosedByCommits',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Auto-generated and auto-updated field',
                                       verbose_name='updated'),
        ),
        migrations.AlterModelTable(
            name='defectclosedbycommits',
            table='testing_defect_closed_by_commits',
        ),
        migrations.AddField(
            model_name='TestAssociatedFiles',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Auto-generated field', verbose_name='created'),
        ),
        migrations.AddField(
            model_name='TestAssociatedFiles',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Auto-generated and auto-updated field',
                                       verbose_name='updated'),
        ),
        migrations.AlterModelTable(
            name='testassociatedfiles',
            table='testing_test_associated_files',
        ),
        migrations.AddField(
            model_name='TestAssociatedAreas',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Auto-generated field', verbose_name='created'),
        ),
        migrations.AddField(
            model_name='TestAssociatedAreas',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Auto-generated and auto-updated field',
                                       verbose_name='updated'),
        ),
        migrations.AlterModelTable(
            name='testassociatedareas',
            table='testing_test_associated_areas',
        ),
    ]
