# Generated by Django 3.2.12 on 2022-04-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0017_auto_20220329_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='type',
            field=models.IntegerField(choices=[(1, 'ENVIRONMENTAL'), (2, 'FLAKY'), (3, 'PROJECT'), (4, 'INVALID TEST'), (5, 'LOCAL'), (6, 'OUTSIDE SCOPE'), (7, 'NEW TEST')], default=1),
        ),
        migrations.AlterField(
            model_name='defectcausedbycommits',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, help_text='Auto-generated and auto-updated field', verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='defectclosedbycommits',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, help_text='Auto-generated and auto-updated field', verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='testassociatedareas',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, help_text='Auto-generated and auto-updated field', verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='testassociatedfiles',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, help_text='Auto-generated and auto-updated field', verbose_name='updated'),
        ),
    ]
