# Generated by Django 3.2.12 on 2022-07-06 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0019_add_materialized_view_for_test_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRunMaterializedModel',
            fields=[
                ('test_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mv_test_count_by_type', serialize=False, to='testing.testrun')),
                ('tests_count', models.IntegerField()),
                ('passed_tests_count', models.IntegerField()),
                ('skipped_tests_count', models.IntegerField()),
                ('failed_tests_count', models.IntegerField()),
                ('broken_tests_count', models.IntegerField()),
                ('not_run_tests_count', models.IntegerField()),
                ('execution_time', models.FloatField()),
                ('status', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'mv_test_count_by_type',
                'managed': False,
            },
        ),
    ]
