#!/bin/bash

set -o errexit
set -o nounset

python manage.py migrate --no-input || :
python manage.py collectstatic --no-input || :
python manage.py auto_createsuperuser || :

gunicorn system.wsgi:application \
--chdir /opt/app/python \
--bind 0.0.0.0:9000 \
--workers 8 \
--graceful-timeout 1200 \
--timeout 1200 \
--worker-class gevent \
--max-requests 512 \
--reload \
--capture-output \
--access-logfile=/opt/app/logs/gunicorn-access.log \
--error-logfile=/opt/app/logs/gunicorn-error.log
