#!/bin/bash
set -e
set -o errexit
set -o nounset

cp /opt/app/crons/cron-notify /etc/cron.d/cron
crontab /etc/cron.d/cron
service postfix start && /usr/sbin/cron -f && tail -f /opt/app/logs/notification.log