# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-24 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='extra_params',
            field=models.JSONField(blank=True, default={'alert_areas': {'enable': False, 'value': None}, 'alert_authors': {'enable': False, 'value': None}, 'alert_commit_changed_code': {'enable': False, 'value': None}, 'alert_commit_time_frame': {'enable': False, 'value': {'end_datetime': None, 'start_datetime': None}}, 'alert_commit_weekday': {'enable': False, 'value': []}, 'alert_committer': {'enable': False, 'value': None}, 'alert_files': {'enable': False, 'value': None}, 'alert_lines': {'enable': False, 'value': None}, 'monitor_areas': [], 'monitor_files': []}),
        ),
    ]
