# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-06 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20191024_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='one_off_end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='one_off_start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='period',
            field=models.IntegerField(blank=True, choices=[(0, 'immediately'), (1, 'daily'), (2, 'weekly'), (3, 'fortnightly'), (4, 'one off')], default=0),
        ),
    ]
