# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-19 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20191206_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='period',
            field=models.IntegerField(blank=True, choices=[(0, 'Immediately'), (1, 'Daily'), (2, 'Weekly'), (3, 'Fortnightly'), (4, 'One Off')], default=0),
        ),
    ]
