# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-07 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20200127_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='period',
            field=models.IntegerField(blank=True, choices=[(0, 'immediately'), (1, 'daily'), (2, 'weekly'), (3, 'fortnightly'), (4, 'One Off')], default=0),
        ),
    ]
