name: Deploy development

on:
  workflow_dispatch:
  push:
    branches: [development]

#env:
#  AZURE_FUNCTIONAPP_NAME_DEVELOPMENT:  ajdashtestdev-function # set this to your application's name
#  AZURE_WEBAPP_NAME_DEVELOPMENT: ajdashtestdev-appservice
#  AZURE_FUNCTIONAPP_PACKAGE_PATH_DEVELOPMENT: 'AskJenna'    # set this to the path to your web app project, defaults to the repository root
#  AZURE_FUNCTIONAPP_PACKAGE_TEST_PATH_DEVELOPMENT: 'AskJenna.Test'
#  AZURE_WEBAPP_PACKAGE_CLIENT_PATH_DEVELOPMENT: 'AskJenna.client'
#  DOTNET_VERSION_DEVELOPMENT: '3.1'              # set this to the dotnet version to use


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2

      - name: Checkout tools
        uses: actions/checkout@v3
        with:
          repository: Appsurify/appsurify-testbrain-deploy
          path: tools
          token: ${{ secrets.DEPLOY_GIT_TOKEN }}
#
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: true
#          tags: docker.io/appsurifyinc/testbrain-core:latest
#          file: compose/testbrain/core/Dockerfile
#          cache-from: type=registry,ref=docker.io/appsurifyinc/testbrain-core:latest

      - uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - uses: azure/aks-set-context@v2.0
        with:
          resource-group: "rg-aks-testbrain-dev"
          cluster-name: "aks-testbrain-dev"

      - uses: azure/setup-kubectl@v2.0
 #       with:
 #         version: '<version>' # default is latest stable
        id: install

      - run: |
          kubectl tools/azure/aks/dev/statefulsets

