# Generated by Django 3.2.12 on 2022-07-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_ssh_v2_integration', '0004_auto_20211229_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitsshv2repository',
            name='is_installed_hook',
            field=models.BooleanField(default=True),
        ),
    ]
