# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-17 11:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0004_project_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerforceRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.CharField(blank=True, default=b'1666', max_length=6)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('client', models.CharField(blank=True, max_length=255)),
                ('depot', models.CharField(blank=True, max_length=255)),
                ('detect_branches', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perforce_repository', to='project.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perforce_repository', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Perforce repository',
                'verbose_name_plural': 'Perforce repositories',
            },
        ),
    ]
