# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-27 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perforce_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perforcerepository',
            name='client',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='perforcerepository',
            name='depot',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='perforcerepository',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
